### ISSUE TITLE
Required file missing

### ISSUE THREAD

**Issue by amiltonwong** [hanfeiid/SRAL#1]
Hi, @hanfeiid ,

According to you code, 'nordland_pr.m' 

```
load colorfeature.mat;
load GISTfeature.mat;
load HOGfeature.mat;
load LBPfeature.mat;
```

These four .mat files are needed. Could you provide them?

Thanks~

**Comment by hanfeiid** [comment]
Hi, @amiltonwong ,

Thank you for the feedback. Due to the file size limitations of Github, we put our .mat files at https://inside.mines.edu/~fhan/publication/code/data/sral/features_mat.zip 

Please let me know if you have any question.

Thanks,
Fei
